# Generated by Django 4.1.6 on 2023-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='task_name')),
                ('text', models.CharField(max_length=255, verbose_name='task_text')),
                ('time', models.IntegerField(verbose_name='task_add_time')),
            ],
        ),
    ]
